---
# tasks file for ansible-role-fgci-install
#
- name: install EPEL
  yum: name=epel-release state=present

- name: creates dhcp.d directory
  file: path=/etc/dhcp/dhcpd.d state=directory

- name: creates nodes.conf file
  file: path=/etc/dhcp/dhcpd.d/nodes.conf state=touch owner=root mode=0644

- name: template in /var/www/html/pull_variables.yml
  template: src=pull_variables.yml.j2 dest=/var/www/html/pull_variables.yml mode=0644 owner=apache group=apache backup=yes

- name: copy hosts file to /var/www/html/hosts.yml - for ansible-pull
  copy: src=hosts dest=/var/www/html/hosts mode=0644 owner=apache group=apache backup=yes

- name: copy the ansible-pull-script.sh to /var/www/html/hosts.yml - for ansible-pull
  copy: src=tools/ansible-pull-script.sh dest=/var/www/html/ansible-pull-script.sh mode=0644 owner=apache group=apache backup=yes
