---
# tasks file for ansible-role-fgci-install
#
# service.yml - the node that runs dhcpd
 - include: service.yml
   when: fgci_node_type == "service"

# compute.yml - the node that runs ansible-pull
 - include: compute.yml
   when: fgci_node_type == "compute"
