---
# tasks file for ansible-role-fgci-install
#
# service.yml - the node that runs dhcpd
 - include_tasks: service.yml
   when: "'slurm_service' in group_names"

# compute.yml - the node that runs ansible-pull
 - include_tasks: compute.yml
   when: "'slurm_compute' in group_names"
