---
# tasks file for ansible-role-fgci-install
#
- name: install EPEL
  yum: name=epel-release state=present

- name: creates dhcp.d directory
  file: path=/etc/dhcp/dhcpd.d state=directory

- name: creates nodes.conf file
  file: path=/etc/dhcp/dhcpd.d/nodes.conf state=touch owner=root mode=0644

- name: template in /var/www/html/pull_variables.yml
  template: src=pull_variables.yml.j2 dest=/var/www/html/pull_variables.yml mode=0644 owner=apache group=apache backup=yes
